<a href="https://colab.research.google.com/github/Anonymous3017/AI-ML-Training/blob/main/Day_5_Ayush_(1)_Track_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem statement(Probability of an event)

Consider that you have a coin and dice. Each time you roll them, you get a result, so try to solve the given questions based on coins and dice.

1.Roll the dice twice and find the probability of getting the number 6 each time.

2.Roll two dice at a time and find the probability of getting a sum of both dice greater than 9.

3.Flip a coin three times continuously and find the probability of getting three heads in a row.

4.Flip a coin anddice simultaneously and find the probability of getting head on the coin and number 5 on the dice simultaneously.

5.Card is drawn at random from the pack of 52 cards:

I.Find the probability that it is an honor card.

II.It is a face card of a diamond house.

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# Define a function to simulate rolling a dice
def roll_dice():
    return np.random.randint(1, 7)

In [ ]:
def flip_coin():
    return np.random.choice(['H', 'T'])

In [ ]:
# 1. Roll the dice twice and find the probability of getting the number 6 each time.
def prob_two_sixes():
    trials = 100000
    count = 0
    for _ in range(trials):
        if roll_dice() == 6 and roll_dice() == 6:
            count += 1
    return count / trials
prob_two_sixes()

0.0281

In [ ]:
# 2. Roll two dice at a time and find the probability of getting a sum of both dice greater than 9.
def prob_sum_greater_than_9():
    trials = 100000
    count = 0
    for _ in range(trials):
        if roll_dice() + roll_dice() > 9:
            count += 1
    return count / trials

prob_sum_greater_than_9()

0.16638

In [ ]:
# 3. Flip a coin three times continuously and find the probability of getting three heads in a row.
def prob_three_heads():
    trials = 100000
    count = 0
    for _ in range(trials):
        if flip_coin() == 'H' and flip_coin() == 'H' and flip_coin() == 'H':
            count += 1
    return count / trials
prob_three_heads()

0.12607

In [ ]:
# 4. Flip a coin and dice simultaneously and find the probability of getting head on the coin and number 5 on the dice simultaneously.
def prob_head_and_5():
    trials = 100000
    count = 0
    for _ in range(trials):
        if flip_coin() == 'H' and roll_dice() == 5:
            count += 1
    return count / trials
prob_head_and_5()

0.08299

In [ ]:
# 5. Card is drawn at random from the pack of 52 cards:

# I. Find the probability that it is an honor card.
total_cards = 52
honor_cards = 16
prob_honor_card = honor_cards / total_cards
print("Probability of drawing an honor card:", prob_honor_card)

Probability of drawing an honor card: 0.3076923076923077

In [ ]:
diamond_face_cards = 3
prob_diamond_face_card = diamond_face_cards / total_cards
print("Probability of drawing a face card of a diamond house:", prob_diamond_face_card)

Probability of drawing a face card of a diamond house: 0.057692307692307696

In [ ]:
total_students = 100
total_boys = 23 + 17 + 10
total_girls = total_students - total_boys

maths_boys = 23
maths_girls = 15

science_boys = 17
science_girls = 23

english_boys = 10
english_girls = 12

# 1. Probability that a student loves Science subject
prob_science = (science_boys + science_girls) / total_students
print("Probability that a student loves Science subject:", prob_science)

Probability that a student loves Science subject: 0.4

In [ ]:
# 2. Probability that a student is a girl and loves Maths subject or English subject

prob_girls_maths_or_english = (maths_girls + english_girls) / total_students
print("Probability that a student is a girl and loves Maths subject or English subject:", prob_girls_maths_or_english)

Probability that a student is a girl and loves Maths subject or English subject: 0.27

In [ ]:
# 3. Probability that a student loves English if she is a girl, or loves Maths if he is a boy

prob_english_girls = english_girls / total_girls
prob_maths_boys = maths_boys / total_boys
prob_loves_english_or_maths = prob_english_girls + prob_maths_boys
print("Probability that a student loves English if she is a girl, or loves Maths if he is a boy:", prob_loves_english_or_maths)

Probability that a student loves English if she is a girl, or loves Maths if he is a boy: 0.7

In [ ]:
df = pd.read_csv("/content/kerala_floods.csv")

In [ ]:
df.head()

,SUBDIVISION,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL RAINFALL,FLOODS
0,KERALA,1901,28.7,44.7,51.6,160.0,174.7,824.6,743.0,357.5,197.7,266.9,350.8,48.4,3248.6,YES
1,KERALA,1902,6.7,2.6,57.3,83.9,134.5,390.9,1205.0,315.8,491.6,358.4,158.3,121.5,3326.6,YES
2,KERALA,1903,3.2,18.6,3.1,83.6,249.7,558.6,1022.5,420.2,341.8,354.1,157.0,59.0,3271.2,YES
3,KERALA,1904,23.7,3.0,32.2,71.5,235.7,1098.2,725.5,351.8,222.7,328.1,33.9,3.3,3129.7,YES
4,KERALA,1905,1.2,22.3,9.4,105.9,263.3,850.2,520.5,293.6,217.2,383.5,74.4,0.2,2741.6,NO

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   SUBDIVISION       118 non-null    object
 1   YEAR              118 non-null    int64
 2   JAN               118 non-null    float64
 3   FEB               118 non-null    float64
 4   MAR               118 non-null    float64
 5   APR               118 non-null    float64
 6   MAY               118 non-null    float64
 7   JUN               118 non-null    float64
 8   JUL               118 non-null    float64
 9   AUG               118 non-null    float64
 10  SEP               118 non-null    float64
 11  OCT               118 non-null    float64
 12  NOV               118 non-null    float64
 13  DEC               118 non-null    float64
 14   ANNUAL RAINFALL  118 non-null    float64
 15  FLOODS            118 non-null    object
dtypes: float64(13), int64(1), object(2)
memory usage: 14.9+ KB

In [ ]:
df.describe()

,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL RAINFALL
count,118.000000,118.000000,118.000000,118.000000,118.000000,118.000000,118.000000,118.000000,118.000000,118.000000,118.000000,118.000000,118.000000,118.000000
mean,1959.500000,12.218644,15.633898,36.670339,110.330508,228.644915,651.617797,698.220339,430.369492,246.207627,293.207627,162.311017,40.009322,2925.405085
std,34.207699,15.473766,16.406290,30.063862,44.633452,147.548778,186.181363,228.988966,181.980463,121.901131,93.705253,83.200485,36.676330,452.169407
min,1901.000000,0.000000,0.000000,0.100000,13.100000,53.400000,196.800000,167.500000,178.600000,41.300000,68.500000,31.500000,0.100000,2068.800000
25%,1930.250000,2.175000,4.700000,18.100000,74.350000,125.050000,535.550000,533.200000,316.725000,155.425000,222.125000,93.025000,10.350000,2613.525000
50%,1959.500000,5.800000,8.350000,28.400000,110.400000,184.600000,625.600000,691.650000,386.250000,223.550000,284.300000,152.450000,31.100000,2934.300000
75%,1988.750000,18.175000,21.400000,49.825000,136.450000,264.875000,786.975000,832.425000,500.100000,334.500000,355.150000,218.325000,54.025000,3170.400000
max,2018.000000,83.500000,79.000000,217.200000,238.000000,738.800000,1098.200000,1526.500000,1398.900000,526.700000,567.900000,365.600000,202.300000,4473.000000

In [ ]:
# 2. Create a DataFrame with columns for June and July rainfall greater than 500mm and whether it flooded that year

df["FLOODS"] = (df["JUN"] > 500) | (df["JUL"] > 500)
flood_prob_df = df[["YEAR", "JUN", "JUL", "FLOODS"]].copy()
flood_prob_df["JUN_GT_500"] = flood_prob_df["JUN"] > 500
flood_prob_df["JUL_GT_500"] = flood_prob_df["JUL"] > 500
flood_prob_df.head()

   YEAR     JUN     JUL  FLOODS  JUN_GT_500  JUL_GT_500
0  1901   824.6   743.0    True        True        True
1  1902   390.9  1205.0    True       False        True
2  1903   558.6  1022.5    True        True        True
3  1904  1098.2   725.5    True        True        True
4  1905   850.2   520.5    True        True        True

In [ ]:
# 3. Calculate the probability of flood given it rained more than 500 mm in June (P(A|B))
prob_flood_given_june_gt_500 = flood_prob_df[flood_prob_df["JUN_GT_500"]]["FLOODS"].mean()

print("\nProbability of flood given it rained more than 500 mm in June ", prob_flood_given_june_gt_500)

Probability of flood given it rained more than 500 mm in June  1.0

In [ ]:
# 4. Calculate the probability of rain more than 500 mm in June, given it flooded that year (P(B|A))
prob_june_gt_500_given_flood = flood_prob_df[flood_prob_df["FLOODS"]]["JUN_GT_500"].mean()
print("\nProbability of rain more than 500 mm in June, given it flooded that year :", prob_june_gt_500_given_flood)

Probability of rain more than 500 mm in June, given it flooded that year : 0.808695652173913

In [ ]:

# 5. Probability of flood given it rained more than 500 mm in July

prob_flood_given_july_gt_500 = flood_prob_df[flood_prob_df["JUL_GT_500"]]["FLOODS"].mean()

print("\nProbability of flood given it rained more than 500 mm in July:", prob_flood_given_july_gt_500)

Probability of flood given it rained more than 500 mm in July: 1.0

In [ ]:
# 6. Probability of rain more than 500 mm in July given it flooded that year (P(B|A))

prob_july_gt_500_given_flood = flood_prob_df[flood_prob_df["FLOODS"]]["JUL_GT_500"].mean()

print("\nProbability of rain more than 500 mm in July given it flooded that year :", prob_july_gt_500_given_flood)

Probability of rain more than 500 mm in July given it flooded that year : 0.8347826086956521